export const GET_RECOMMEND_BANNER = 'GET_RECOMMEND_BANNER';

export const SET_CHANGE_INDEX = 'SET_CHANGE_INDEX';

export const GET_PLAYLIST_CATLIST = 'GET_PLAYLIST_CATLIST';

export const GET_RECOMMEND_LIST = 'GET_RECOMMEND_LIST';

export const PREVIOUS_INDEX = 'PREVIOUS_INDEX';

export const CURRENT_INDEX = 'CURRENT_INDEX';

export const NEW_ALBUM_LIST = 'NEW_ALBUM_LIST';

export const ALL_TOP_LIST = 'ALL_TOP_LIST';

export const GET_UPPLAYLIST_DETAIL = 'GET_UPPLAYLIST_DETAIL ';

export const GET_NEWPLAYLIST_DETAIL = 'GET_NEWPLAYLIST_DETAIL';

export const GET_ORIGINPLAYLIST_DETAIL = 'GET_ORIGINPLAYLIST_DETAIL';
